matrix:
- name: Markdown
  apsell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  sources:
  - '**/*.md'
  
