title: OpenSearch SDK for Java 
description: Extension Documentation
logo: /assets/img/logo.png

remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
  - jekyll-remote-theme

color_scheme: opensearch