title: OpenSearch SDK for Java Extension Documentation
description: Learn how to create extensions for OpenSearch
remote_theme: pmarsceill/just-the-docs@v0.3.3

url: https://kolchfa-aws.github.io/test-repo

aux_links:
  OpenSearch Documentation: https://opensearch.org/docs/