title: Extensions
description: OpenSearch SDK for Java Extension Documentation
remote_theme: pmarsceill/just-the-docs@v0.3.3

url: https://kolchfa-aws.github.io/test-repo

aux_links:
  OpenSearch Documentation: https://opensearch.org/docs/

color_scheme: opensearch