title: OpenSearch SDK for Java 
description: Extension Documentation
theme: jekyll-theme-minimal
logo: /assets/img/logo.png

sidenav:
  - name: Design
    link: DESIGN.html
  - name: Developer Guide
    link: DEVELOPER_GUIDE.html
  - name: Create your first extension
    link: CREATE_YOUR_FIRST_EXTENSION.html
  - name: Plugin migration
    link: PLUGIN_MIGRATION.html
