title: OpenSearch SDK for Java 
description: Extension Documentation
theme: jekyll-theme-minimal
logo: logo.png
show_downloads: true

sidenav:
  - name: Design
    link: /DESIGN.html
  - name: Developer Guide
    link: DEVELOPER_GUIDE.md
  - name: Create your first extension
    link: CREATE_YOUR_FIRST_EXTENSION.md
  - name: Plugin migration
    link: PLUGIN_MIGRATION.md
