theme: just-the-docs
title: OpenSearch SDK for Java Extension Documentation
description: Learn how to create extensions for OpenSearch

url: https://kolchfa-aws.github.io/test-repo

aux_links:
  OpenSearch Documentation: https://opensearch.org/docs/