extends: substitution
message: "Use above and below only for physical space or screen descriptions. Use '%s' instead of '%s' for orientation within a document."
link: 'https://github.com/opensearch-project/documentation-website/blob/main/TERMS.md'
level: warning
ignorecase: true
swap:
  - above: 'previous, preceding, earlier, following'
  - below: later
