extends: conditional
message: "'%s': Spell out acronyms the first time that you use them on a page and follow them with the acronym in parentheses. On subsequent use, use the acronym alone."
link: 'https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#acronyms'
level: warning
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - 3D
  - API
  - ASCII
  - BASIC
  - BM25
  - CPU
  - DOS
  - FAQ
  - FTP
  - GIF
  - HTML
  - HTTP
  - HTTPS
  - ID
  - IP
  - JPEG
  - JSON
  - NAT
  - NGINX
  - PDF
  - RAM
  - REST
  - RGB
  - ROM
  - SAML
  - SDK
  - SSL
  - TCP
  - TIFF
  - TLS
  - UI
  - URI
  - URL
  - UTC
  - UTF
  - XML
  - YAML
