extends: existence
message: "Don't use a comma after single-word adverbs of time at the beginning of a sentence '%s'."
level: error
ignorecase: false
nonword: true
tokens:
  - '(?:[^\s]Then|Afterward|Later|Subsequently),'
