extends: existence
message: "There should be no spaces around the '%s' dash."
ignorecase: true
scope: text
nonword: true
level: error
tokens:
  - '\w+ +-{2,3} +\w+'
  - '\w+-{2,3} +\w+'
  - '\w+ +-{2,3}\w+'
