extends: sequence
scope: heading
message: "Headings should start with a present participle phrase or a noun phrase. Don't start a heading with '%[2]s'."
tokens:
  - pattern: "^"
  - tag: VBD|VBN|VBP|VBZ
 
