extends: existence
message: "Using '%s' is unnecessary. Remove."
link: https://github.com/opensearch-project/documentation-website/blob/main/STYLE_GUIDE.md#basic-guidelines
ignorecase: true
level: warning
tokens:
  - '\b(?:etc|etc\.)'
