extends: existence
message: "'%s': There should be no space before and one space after the punctuation mark."
level: error
nonword: true
tokens:
  - '[A-Za-z][.?] {2,}[A-Z]'
  - '[A-Za-z][.?][A-Z]'
  - '[A-Za-z] +[.?,;:]'
  - '[A-Za-z][,;:] {2,}[A-Za-z]'
  - '[A-Za-z][,;:][A-Za-z]'
