extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  'command-line interface': command line interface
  'for information on': for information about
  'for more information on': for more information about
  'geo hash': geohash
  'high-performance computing': high performance computing
  'indices': indexes
  'machine-learning': machine learning
  'nonproduction': non-production
  'postmigration': post-migration
  'pre-configure': preconfigure
  'pre-configured': preconfigured
  'pre-defined': predefined
  'pre-train': pretrain
  'pre-trained': pretrained
  'premigration': pre-migration
  're-enable': reenable
  'sample request': example request
  'sample response': example response
  'stand-alone': standalone
  'web page': webpage
  'web site': website
