extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: suggestion
swap:
  'app server': application server
  'as well as': 'in addition to/and'
  'due to': because of
  'it is recommended': we recommend
  'leverage': use
  'life cycle': lifecycle
  'navigate in': navigate to
  'wish|desire': want
  'repo': repository
  
