extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: suggestion
swap:
  'it is recommended': we recommend
  'repo': repository
  'as well as': 'in addition to/and'
  'app server': application server
