extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  'for information on': for information about
  'for more information on': for more information about
  'image below': following image
  'sample request': example request
  'sample response': example response
  'indices': indexes 
