extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: false
level: error
swap:
  '[Ff]or information on': '[Ff]or information about'
  'for more information on': for more information about
  'image below': following image
