extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  'command-line interface': command line interface
  'data set': dataset
  'for information on': for information about
  'for more information on': for more information about
  'geo hash': geohash
  'geospacial': geospatial
  'hard code': hardcode
  'high-performance computing': high performance computing
  'host name': hostname
  'indices': indexes
  'kmeans': k-means
  'kNN': k-NN
  'machine-learning': machine learning
  'nonproduction': non-production
  'postmigration': post-migration
  'pre-configure': preconfigure
  'pre-configured': preconfigured
  'pre-defined': predefined
  'pre-train': pretrain
  'pre-trained': pretrained
  'premigration': pre-migration
  're-enable': reenable
  'screen shot': screenshot
  'sample request': example request
  'sample response': example response
  'stand-alone': standalone
  'time series data': time-series data
  'time stamp': timestamp
  'timezone': time zone
  'U.S.': US
  'web page': webpage
  'web site': website

