extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  'for information on': for information about
  'for more information on': for more information about
  'image below': following image
  'sample request': example request
  'sample response': example response
  'indices': indexes 
  'pre-trained': pretrained
  'pre-train': pretrain
  'stand-alone': standalone
  'geo hash': geohash
  'command-line interface': command line interface
  'high-performance computing': high performance computing
  'machine-learning': machine learning
  'nonproduction': non-production
  'postmigration': post-migration
  'premigration': pre-migration
  'pre-defined': predefined
