extends: sequence
message: "Rewrite '%s' to focus on the topic's subject."
ignorecase: false
level: suggestion
tokens:
  - pattern: The 
  - pattern: following 
  - pattern: 'section|page|document'
  - tag: VBZ
