name: Check spelling with cspell

on:
  workflow_dispatch:
  #push:
  #pull_request:
   

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root: '.'
          config: './cspell.config.yaml'
          files: "**/*.md"
          incremental_files_only: true
          strict: true
