name: Check links on push

on:
  #push:
  #pull_request:
   
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: 'link-checker-config.json'
        check-modified-files-only: 'yes'
        base-branch: 'main'
