name: Spellcheck
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:
  
jobs:
  spellcheck-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.29.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt
      - name: Comment on the PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: 'spellcheck-output.txt'
