name: Style check

on:
  #push:
    #branches:
      #- main
  pull_request:
    #branches:
      #- main
    
  workflow_dispatch:

jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'
          
      - name: Print files
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Vale will run on ${changed_file}."
          done
          
      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: true
          reporter: github-pr-check
          filter_mode: file
          files: '${{  steps.files.outputs.added_modified }}'


