name: Style check

on:
  #push:
    #branches:
      #- main
  pull_request:
    #branches:
      #- main
    
  workflow_dispatch:

jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
     
      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','
          fileOutput: ','

      - name: Run vale
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: false
          reporter: github-pr-check
          files: '${{ steps.file_changes_outputs_files }}'
          separator: ','
          
