name: Style check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

jobs:
  style-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run vale
        uses: errata-ai/vale-action@reviewdog
        with:
          debug: true
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
